CC = gcc

CFLAGS = -Wall -Wextra -O3
LDFLAGS = -lm

ifeq ($(OS),Windows_NT)
    EXE = .exe
    RM = del /Q
else
    EXE =
    RM = rm -f
endif

all: cgSolver v1 v2 v3

cgSolver:
	$(CC) $(CFLAGS) conjugated_method.c -o cgSolver$(EXE) $(LDFLAGS)

v1:
	$(CC) $(CFLAGS) conjugated_methodv1.c -o conjugated_methodv1$(EXE) $(LDFLAGS)

v2:
	$(CC) $(CFLAGS) conjugated_methodv2.c -o conjugated_methodv2$(EXE) $(LDFLAGS)

v3:
	$(CC) $(CFLAGS) conjugated_methodv3.c -o conjugated_methodv3$(EXE) $(LDFLAGS)

clean:
	$(RM) *$(EXE)