CC = gcc

CFLAGS = -Wall -Wextra
LDFLAGS = -lm

SRC = cgSolver.c

ifeq ($(OS),Windows_NT)
    TARGET = cgSolver.exe
    RM = del /Q
else
    TARGET = cgSolver
    RM = rm -f
endif

all: release

debug: CFLAGS += -O0 -g
debug: $(TARGET)

release: CFLAGS += -O3
release: $(TARGET)

$(TARGET): $(SRC)
	$(CC) $(CFLAGS) $(SRC) -o $(TARGET) $(LDFLAGS)

clean:
	$(RM) $(TARGET)